### ISSUE TITLE
support for setting Cell Hyperlinks

### ISSUE THREAD

**Issue by shaun-madison** [mk-j/PHP_XLSXWriter#112] opened 2017-05-03 14:37 UTC
do you have any plans for adding support for Cell Hyperlinks? As all the openxml infrastructure is there it would be seem reasonably straight forward to add this useful capability.

**Comment by mk-j** [comment] 2017-05-03 18:39
Thanks for your interest in this project, there seems to be significant interest in this feature.  We might look at adding the functionality in the coming months.

**Comment by mk-j** [comment] 2017-05-19 17:34
duplicate of #74

**Comment by Yursksf1** [comment] 2018-04-12 15:54
Hi, look this example 
`````` php
<?php
set_include_path( get_include_path().PATH_SEPARATOR."..");
include_once("xlsxwriter.class.php");

// integer is Int, price is float
$header = array(
    'name'=>'string',
    'link'=>'string',
    'hiperlink'=>'string',
);
$data1 = array(
    array('Google','www.google.com','=HYPERLINK("http://www.google.com","Google")'),
    array('Facebook','www.facebook.com','=HYPERLINK("http://www.facebook.com","Facebook")'),
    array('GitHub','www.github.com','=HYPERLINK("http://www.github.com","GitHub")'),
    array('LinkedIn','www.linkedin.com','=HYPERLINK("http://www.linkedin.com","Linkedin")'),
    array('Twitter','www.twitter.com','=HYPERLINK("http://www.twitter.com","Twitter")'),
);
$writer = new XLSXWriter();
$writer->writeSheetHeader('Sheet1', $header);
foreach($data1 as $row)
	$writer->writeSheetRow('Sheet1', $row);
$writer->writeToFile('example-hiperlink.xlsx');
//$writer->writeToStdOut();
//echo $writer->writeToString();

exit(0);
``````
Result: 
![image](https://user-images.githubusercontent.com/25001142/38688842-b589633c-3e3f-11e8-86f3-2b92742ac1a8.png)

[example-hiperlink.xlsx](https://github.com/mk-j/PHP_XLSXWriter/files/1903954/example-hiperlink.xlsx)

**Comment by hhh062001** [comment] 2020-12-04 00:17
How to add multiple links in one cell?

**Closed** 2023-05-31 17:14 UTC
